Store the queue in PostgreSQL
camptocamp/tilecloud-chain pull request #2124
Opened 2023-10-26 10:53 UTC by sbrunner

2023-11-02 08:29 UTC, danduk82 requested changes
The code is good to me, but I think that a there should be a dedicated section in the README, so that we know how to configure it.
The example is quite cryptic as the `postgres: {}` section actually requires some env variables to really work.
Actually, is the `postgres: {}` section really useful, can it be filled with some entries? If yes which ones? Or could it be only removed and replaced with an env variable like `TILECLOUD_CHAIN_MAIN_QUEUE_STORE=postgres` ?

2023-11-02 09:08 UTC, danduk82 approved these changes

2023-11-03 10:18 UTC, danduk82 approved these changes
looks good

2023-11-03 10:44 UTC, merged

2023-11-03 10:44 UTC, sbrunner commented
Thanks :-)